stages:
  - setup
  - test


setup_environment:
  stage: setup
  image: python:3.10
  before_script:
    - pip install poetry
  script:
    - poetry install --with dev --extras "rxnmapper"


run_tests:
  stage: test
  image: python:3.10
  before_script:
    - pip install poetry
    - poetry install --with dev --extras "rxnmapper"
  script:
    - poetry run pytest tests --ignore=tests/end_to_end/
